[project]
name = "anki-chess-opening-trainer"
version = "1.1.0"
requires-python = "==3.12.*"
dependencies = [
    "chess==1.10.0",
    "semantic_version==2.10.0",
    "jsonschema==4.22.0",
    "typing_extensions==4.12.1",
]

[dependency-groups]
# These are your testing/development requirements from dev.txt
dev = [
    "anki==23.10",
    "aqt==23.10",
    "PyQt6-WebEngine",
    "ankiscripts",
    "yapf",
    "isort",
    "mypy",
	"pip",
    "pylint",
    "pytest==8.2.1",
    "pytest-cov==5.0.0",
    "datamodel-code-generator==0.25.6",
]

[tool.uv.sources]
ankiscripts = { git = "https://github.com/abdnh/ankiscripts", rev = "ed96ad699fe9dd52e6baec92e4619664fe28fd15" }

[tool.yapf]
based_on_style = "pep8"

# See https://lea.verou.me/blog/2012/01/why-tabs-are-clearly-superior/.
use_tabs = "True"

i18n_comment = "# TRANSLATORS:"
i18n_function_call = ["_", "ngettext"]


[tool.yapfignore]
ignore_patterns = [
	"src/forms/**/*",
	"src/vendor/**/*"
]

[tool.isort]
skip = [
	"src/forms/**/*",
	"src/vendor/**/*"
]

[tool.pylint.main]
# This module is not meant to be reused.  For the time being, I do not
# bother to write docstrings.
disable = ["C0114", "C0115", "C0116"]

[tool.pylint.format]
indent-string = "\\t"

[tool.pylint.string]
check-quote-consistency = true

[tool.pylint.variables]
additional-builtins = ["_", "ngettext"]

[[tool.mypy.overrides]]
module = "semantic_version.*"
ignore_missing_imports = true

